name: Push Updates

on:
  workflow_dispatch:

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Dockerhub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Github CR Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUBCR_USERNAME }}
        password: ${{ secrets.GITHUBCR_PASSWORD }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Amazon ECR Login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Run Builder Script
      run: python3 builder.py
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1

    - name: Clear Docker Credentials
      if: always()
      run: rm -f ${HOME}/.docker/config.json
